name: BentoML CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push BentoML Image
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt

      # 4. Save the latest model to BentoML
      - name: Save the latest model to BentoML
        working-directory: src
        run: |
          python save_model.py

      # 5. Build BentoML service
      - name: Build BentoML service
        working-directory: src/service
        run: |
          bentoml build

      # # 6. Containerize BentoML service
      # - name: Containerize BentoML service
      #   id: containerize
      #   working-directory: src/service
      #   run: |
      #     # Lấy tag mới nhất của Bento
      #     BENTO_TAG=$(bentoml list | grep forecast | head -n 1 | awk '{print $1}')

      #     # Lưu tag của Bento vào biến môi trường
      #     echo "BENTO_TAG=$BENTO_TAG" >> $GITHUB_ENV

      #     # Containerize Bento với tag cụ thể
      #     bentoml containerize $BENTO_TAG 

      #     # Lưu tên image vào biến môi trường
      #     echo "BENTO_IMAGE=$BENTO_TAG" >> $GITHUB_ENV

      # # 7. Log in to Docker Hub
      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      # # 8. Push Docker image to Docker Hub
      # - name: Push Docker image
      #   run: |
      #     docker push ${{ env.BENTO_IMAGE }}
